version: "3.9"
services:
  ha_strat_bot:
    image: freqtradeorg/freqtrade:latest
    container_name: "ha_strat_bot"
    build:
      context: "../."
      dockerfile: "/freqport/Dockerfile"
    volumes:
      - "./bot1:/freqtrade/user_data"
    command: >
      trade --strategy ha_strat 
      -c /freqtrade/user_data/config.json
      -c /freqtrade/user_data/api_keys.json

  bbrsi_strat_bot:
    image: freqtradeorg/freqtrade:latest
    container_name: "bbrsi_strat_bot"
    build:
      context: "../."
      dockerfile: "/freqport/Dockerfile"
    volumes:
      - "./bot2:/freqtrade/user_data"
    command: >
      trade --strategy ha_strat 
      -c /freqtrade/user_data/config.json 
      -c /freqtrade/user_data/api_keys.json

