---
    version: '3'
    services:
      user01:
        image: freqtradeorg/freqtrade
        restart: unless-stopped
        container_name: user01
        build:
          context: ../.
          dockerfile: freqport/ta.dockerfile
        volumes:
          - "./strategies:/freqtrade/user_data/strategies"
          - "./configs:/freqtrade/user_data/configs"
        command: >
          trade
          -c /freqtrade/user_data/configs/default.json
          -c /freqtrade/user_data/configs/keys/user01.json
          --strategy BbandRsi
      user02:
        image: freqtradeorg/freqtrade
        restart: unless-stopped
        container_name: user02
        build:
          context: ../.
          dockerfile: freqport/ta.dockerfile
        volumes:
          - "./strategies:/freqtrade/user_data/strategies"
          - "./configs:/freqtrade/user_data/configs"
        command: >
          trade
          -c /freqtrade/user_data/configs/default.json
          -c /freqtrade/user_data/configs/keys/user02.json
          --strategy GodStra
      user03:
        image: freqtradeorg/freqtrade
        restart: unless-stopped
        container_name: user03
        build:
          context: ../.
          dockerfile: freqport/ta.dockerfile
        volumes:
          - "./strategies:/freqtrade/user_data/strategies"
          - "./configs:/freqtrade/user_data/configs"
        command: >
          trade
          -c /freqtrade/user_data/configs/default.json
          -c /freqtrade/user_data/configs/keys/user03.json
          --strategy Scalp
